version: "3"
services:
  zookeeper:
    image: shubhamlatkar/zookeeper:1
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: shubhamlatkar/kafka:1
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181