eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761

spring:
  main:
    banner-mode: "log"

logging:
  file:
    name: C:/Users/91960/workspace/Mentor-On-Demand/Backend/logs/EUREKA-SERVER.log